import { RoadmapNode, UserProfile } from '../types';
export interface LearningProfileSnapshot { goal: string; interests: string[]; skills: Record<string, number>; targetSkills: Record<string, number>; learningHistory: string[]; weeklyHours: number; learningStyle: string; difficulty: string; }
const domains = ['programming','dataMath','design','communication','leadership','research'];
const labels: Record<string,string> = { programming: 'Programming', dataMath: 'Data and analysis', design: 'Design', communication: 'Communication', leadership: 'Leadership', research: 'Research' };
export function createLearningProfile(input: Partial<LearningProfileSnapshot> & Pick<LearningProfileSnapshot,'goal'>): LearningProfileSnapshot {
  const skills = input.skills || { programming: 35, dataMath: 35, design: 35, communication: 45, leadership: 25, research: 30 };
  return { goal: input.goal.trim(), interests: input.interests || [], skills, targetSkills: input.targetSkills || Object.fromEntries(domains.map(d => [d, 80])), learningHistory: input.learningHistory || [], weeklyHours: input.weeklyHours || 5, learningStyle: input.learningStyle || 'balanced', difficulty: input.difficulty || 'moderate' };
}
export function generatePersonalizedRoadmap(profile: LearningProfileSnapshot | UserProfile): any[] {
  const p = profile as LearningProfileSnapshot; const skills = p.skills || {}; const targets = p.targetSkills || {};
  const focus = domains.slice().sort((a,b) => ((targets[b] || 80) - (skills[b] || 0)) - ((targets[a] || 80) - (skills[a] || 0))).slice(0,4);
  const foundation: any = { id: 'goal-alignment', title: 'Clarify your learning goal', shortDescription: 'Turn your goal into a focused outcome.', type: 'checkpoint', status: 'done', progress: 100, domain: 'communication', whyThis: 'Your goal anchors every recommendation.', whyThisDetail: { summary: 'Trellis uses this step to sequence your path.', factors: ['Goal clarity'], confidence: 96 }, estHours: 1, weekIndex: 1, branchId: 'core', learningModule: { title: 'Goal alignment', lessons: ['Define your outcome'] } };
  const modules = focus.map((domain,index) => { const gap = Math.max(0, Math.min(100, (targets[domain] || 80) - (skills[domain] || 0))); const id = 'skill-' + domain; const previous = index === 0 ? foundation.id : 'skill-' + focus[index - 1]; return { id, title: labels[domain] + ' foundations', shortDescription: 'Build the ' + labels[domain].toLowerCase() + ' needed for your goal.', type: index === 3 ? 'project' : 'course', status: index === 0 ? 'available' : 'locked', progress: 0, domain, whyThis: 'This closes an estimated ' + Math.round(gap) + '-point skill gap.', whyThisDetail: { summary: 'Trellis prioritizes the largest skill gap first.', factors: [Math.round(gap) + '-point gap', (p.learningStyle || 'balanced') + ' practice'], confidence: 88 }, estHours: Math.max(2, Math.round(gap / 18)), weekIndex: index + 1, branchId: index % 2 ? 'practice' : 'core', prerequisites: [previous], requires: [previous], learningModule: { title: labels[domain] + ' foundations', lessons: ['Learn the mental model', 'Practice with a guided example', 'Apply it to your goal'] } }; });
  return [foundation, ...modules, { id: 'capstone', title: 'Ship a proof-of-learning project', shortDescription: 'Combine your new skills into a useful outcome.', type: 'project', status: 'locked', progress: 0, domain: focus[0] || 'programming', whyThis: 'A project tests whether skills transfer to your real goal.', whyThisDetail: { summary: 'Projects turn learning into evidence.', factors: ['Your goal'], confidence: 91 }, estHours: Math.max(4, p.weeklyHours || 5), weekIndex: 4, branchId: 'capstone', prerequisites: modules.map(n => n.id), requires: modules.map(n => n.id), learningModule: { title: 'Capstone project', lessons: ['Define scope', 'Build a first version', 'Reflect and iterate'] } }];
}
export const saveLearningProfile = (profile: LearningProfileSnapshot) => localStorage.setItem('trellis-learning-profile', JSON.stringify(profile));
export const loadLearningProfile = (): LearningProfileSnapshot | null => { try { const raw = localStorage.getItem('trellis-learning-profile'); return raw ? JSON.parse(raw) : null; } catch { return null; } };
export const saveGeneratedRoadmap = (nodes: RoadmapNode[]) => localStorage.setItem('trellis-generated-roadmap', JSON.stringify(nodes));
export const loadGeneratedRoadmap = (): RoadmapNode[] | null => { try { const raw = localStorage.getItem('trellis-generated-roadmap'); return raw ? JSON.parse(raw) : null; } catch { return null; } };

